apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-madrid
  namespace: madrid-p5
spec:
  rules:
  - host: madrid.monitor.es
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prometheus-svc
            port:
              number: 20000