apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway-dep
  namespace: castilla-p5
  labels:
    app: pushgateway
spec:
  replicas: 1 # porque sino puede elegir entre dos pods y no funciona al prometheus pedir la informacion
  selector:
    matchLabels:
      app: pushgateway
  template:
    metadata:
      labels:
        app: pushgateway
    spec:
      containers:
      - name: pushgateway
        image: transactcharlie/pushgateway:latest
        ports:
        - containerPort: 9091
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway-svc
  namespace: castilla-p5
spec:
  type: NodePort
  sessionAffinity: ClientIP
  selector:
    app: pushgateway
  ports:
    - protocol: TCP
      port: 20000
      targetPort: 9091
      nodePort: 30006